export const ROUTER_NAVIGATION = 'ROUTER_NAVIGATION'
export const CHANGE_PAGE_ID = 'CHANGE_PAGE_ID'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_CSRF_TOKEN = 'UPDATE_CSRF_TOKEN'

export const CURRENT_USER_UPDATED = 'CURRENT_USER_UPDATED'
export const CURRENT_USER_REQUESTED = 'CURRENT_USER_REQUESTED'
